Repository googleapis/python-binary-authorization, pull requests merged in 2021-05, with the labels that each got.

#21 chore: Re-generated to pick up changes from synthtool
  .kokoro/release.sh
  .kokoro/release/common.cfg
  docs/_static/custom.css
  synth.metadata
Labels: api: binaryauthorization, cla: yes, context: full

#26 [CHANGE ME] Re-generated to pick up changes from self.
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  noxfile.py
  synth.metadata
Labels: api: binaryauthorization, cla: yes, context: none

#27 chore: add library type to .repo-metadata.json
  .repo-metadata.json
Labels: api: binaryauthorization, automerge, cla: yes

#29 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  owlbot.py
  synth.metadata
Labels: api: binaryauthorization, cla: yes

#34 fix(deps): add packaging requirement
  setup.py
  testing/constraints-3.6.txt
Labels: api: binaryauthorization, automerge, cla: yes

#33 chore: add cicd (devplat) team to codeowners
  .github/CODEOWNERS
Labels: api: binaryauthorization, automerge, cla: yes
